title: Node-OS
description: The first operating system powered by node.js and npm
permalink: /blog/:title
url: "https://node-os.com"
twitter_username: thenodeos
github_username:  nodeos
repository: nodeos/nodeos.github.io

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
paginate: 5
paginate_path: "/blog/page/:num/"
